#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vi="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
       alias $x="sudo $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
        bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
        la="colorls -hAltr --sd" \
        ls="colorls -hltr --sd"

# These common commands are just too long! Abbreviate them.
alias \
        br="sudo lsof +c 0 | grep -w 'DEL.*lib' | awk '{print \$1}' | sort -u" \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
        weechat="weechat -d $XDG_CONFIG_HOME/weechat"

# Work stuff
alias \
        apl="ansible-playbook" \
        azcli="docker run -it -v ${HOME}/.ssh:/root/.ssh mcr.microsoft.com/azure-cli" \
        cdsi="cd ~/.local/git/si-ansible" \
        cpa="scp si-satellite.si.edu:/etc/ansible/hosts . ; sudo cp hosts /etc/ansible/hosts ; rm hosts" \
        gpa='find ~ -name ".git" -type d -exec bash -c "echo '{}' && cd '{}'/.. && git pull" \;' \
        rvim="sudo nvim" \
        sat="ssh si-satellite" \
        swork="ssh work"

vf() { fzf | xargs -r -I % $EDITOR % ;}
